name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.manikarnajampala}}
          password: ${{ secrets.Mani123@rm }}

      - name: Build Docker Image
        run: docker build -t manikarnajampala/python-demo-web:latest .

      - name: Push Docker Image
        run: docker push manikarnajampala/python-demo-web:latest